spring.application.name=esg


# ===============================
# MySQL RDS DB Connection
# ===============================

spring.datasource.url=jdbc:mysql://eatstatgram-db.c1su4acaapv8.ap-northeast-2.rds.amazonaws.com:3306/eatstatgram_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=eatstat_admin
spring.datasource.password=gksk3685
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# MyBatis Settings
# ===============================

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.project.esg
mybatis.configuration.jdbc-type-for-null=NULL

# ===============================
# Server Settings
# ===============================

server.port=9988